# Generated by Django 5.2.10 on 2026-02-11 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_profile_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("capacity", models.PositiveIntegerField()),
                ("rate_per_night", models.DecimalField(decimal_places=2, max_digits=8)),
                ("available_rooms", models.PositiveIntegerField()),
                ("checkin_date", models.DateField()),
                ("checkout_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("hotel", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rooms", to="accounts.profile")),
                ("room_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="rooms.roomtype")),
            ],
        ),
    ]
