# Generated by Django 5.2.10 on 2026-02-11 00:00

from django.db import migrations


def seed_room_types(apps, schema_editor):
    room_type_model = apps.get_model("rooms", "RoomType")
    for name in [
        "Standard Room",
        "Deluxe Room",
        "Executive Suite",
        "Family Suite",
        "Presidential Suite",
    ]:
        room_type_model.objects.get_or_create(name=name)


def unseed_room_types(apps, schema_editor):
    room_type_model = apps.get_model("rooms", "RoomType")
    room_type_model.objects.filter(
        name__in=[
            "Standard Room",
            "Deluxe Room",
            "Executive Suite",
            "Family Suite",
            "Presidential Suite",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_room_types, reverse_code=unseed_room_types),
    ]
