# Generated by Django 5.2.10 on 2026-02-12 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileFacilityImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="facilities/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="facility_images", to="accounts.profile"),
                ),
            ],
        ),
    ]
