# Generated by Django 5.2.10 on 2026-02-12 00:00

from django.db import migrations, models


def set_initial_order(apps, schema_editor):
    facility_model = apps.get_model("accounts", "ProfileFacilityImage")
    for profile_id in facility_model.objects.values_list("profile_id", flat=True).distinct():
        images = facility_model.objects.filter(profile_id=profile_id).order_by("id")
        for index, image in enumerate(images):
            facility_model.objects.filter(id=image.id).update(sort_order=index)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_facility_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilefacilityimage",
            name="sort_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(set_initial_order, reverse_code=noop_reverse),
    ]
