# Generated by Django 5.2.10 on 2026-02-13 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_facility_image_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilefacilityimage',
            options={'ordering': ('sort_order', '-uploaded_at')},
        ),
    ]
